kibot:
  version: 1

outputs:
  - name: "Export_Schema_PDF"
    type: pdf_sch_print
    dir: "Export/Schema" # <-- Modifié pour inclure le dossier parent Export
    options:
      output: "schema_complet.pdf" 

  - name: "Rendu_PCB_Top"
    type: pcbdraw
    dir: "Export/Visuels" # <-- Modifié pour inclure le dossier parent Export
    options:
      format: jpg
      output: "pcb_preview.jpg"   
      show_components: none
