name: "KiCad Visuals Export"

on:
  push:
    branches: [ main ]

jobs:
  Export-and-Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important pour que l'action puisse publier
    steps:
      - name: Checkout du projet
        uses: actions/checkout@v4

      - name: Génération des visuels avec KiBot
        uses: INTI-CMNB/KiBot@v2_k9
        with:
          config: config.kibot.yaml
          schema: 'Carte_arriere_acquisition.kicad_sch'
          board: 'Carte_arriere_acquisition.kicad_pcb'

      - name: Déployer les visuels sur la branche assets
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: assets        # La branche de destination
          folder: Export/       # Le dossier généré par KiBot
          target-folder: images # Dossier de stockage dans la branche assets
          commit-message: "Mise à jour automatique des visuels (KiCad 9)"